
import { Routes } from '@angular/router';
import { LandingComponent } from './pages/landing/landing';
import { HomeComponent } from './pages/products/home';
import { ModelDetailsComponent } from './pages/model-details/model-details';
import { BiochemistryComponent } from './pages/biochemistry/biochemistry';
import { WineryComponent } from './pages/winery/winery';
import { MeatIndustryComponent } from './pages/meat-industry/meat-industry';
import { MiningComponent } from './pages/mining/mining';
import { MunicipalitiesComponent } from './pages/municipalities/municipalities';
import { ContactComponent } from './pages/contact/contact';
import { EcologicalPoolComponent } from './pages/ecological-pool/ecological-pool';
import { ThermalWatersComponent } from './pages/thermal-waters/thermal-waters';
import { DesalinationComponent } from './pages/desalination/desalination';
import { DataCentersComponent } from './pages/data-centers/data-centers';
import { TextileIndustryComponent } from './pages/textile-industry/textile-industry';
import { GreenHydrogenComponent } from './pages/green-hydrogen/green-hydrogen';
import { LeachateComponent } from './pages/leachate/leachate';

export const routes: Routes = [
    { path: '', component: LandingComponent },
    { path: 'products', component: HomeComponent },
    { path: 'category/:category', component: HomeComponent },
    { path: 'model/:category/:id', component: ModelDetailsComponent },
    { path: 'biochemistry/:category', component: BiochemistryComponent },
    { path: 'winery', component: WineryComponent },
    { path: 'meat-industry', component: MeatIndustryComponent },
    { path: 'mining', component: MiningComponent },
    { path: 'municipalities', component: MunicipalitiesComponent },
    { path: 'ecological-pool', component: EcologicalPoolComponent },
    { path: 'thermal-waters', component: ThermalWatersComponent },
    { path: 'desalination', component: DesalinationComponent },
    { path: 'data-centers', component: DataCentersComponent },
    { path: 'textile-industry', component: TextileIndustryComponent },
    { path: 'green-hydrogen', component: GreenHydrogenComponent },
    { path: 'leachate', component: LeachateComponent },
    { path: 'contact', component: ContactComponent },
    { path: '**', redirectTo: '' }
];
