import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../services/language.service';
import { DataService } from '../../services/data.service';
import { AnimatedPulsePillComponent } from '../../components/animated-pulse-pill/animated-pulse-pill.component';
import { CoreTechnologySectionComponent } from '../../components/core-technology-section/core-technology-section.component';
import { MetricCardComponent } from '../../components/metric-card/metric-card.component';
import { TechnicalEvaluationCTAComponent } from '../../components/technical-evaluation-cta/technical-evaluation-cta.component';

@Component({
  selector: 'app-ecological-pool',
  standalone: true,
  imports: [
    CommonModule,
    AnimatedPulsePillComponent,
    CoreTechnologySectionComponent,
    MetricCardComponent,
    TechnicalEvaluationCTAComponent
  ],
  templateUrl: './ecological-pool.html',
  styleUrl: './ecological-pool.css'
})
export class EcologicalPoolComponent {
  lang = inject(LanguageService);
  data = inject(DataService);

  get scienceFacts() {
    return this.data.getScienceStats(this.lang.language())['ecological_pool'] || [];
  }

  /** The real problems ecological pools face without Flowform */
  get problems() {
    const l = this.lang.language();
    return [
      {
        icon: '🟢',
        label: l === 'es' ? 'Agua verde por algas' : 'Green water from algae'
      },
      {
        icon: '🦠',
        label: l === 'es' ? 'Patógenos que persisten' : 'Persistent pathogens'
      },
      {
        icon: '💨',
        label: l === 'es' ? 'Falta de oxigenación' : 'Lack of oxygenation'
      },
      {
        icon: '🍂',
        label: l === 'es' ? 'Desequilibrio biológico' : 'Biological imbalance'
      }
    ];
  }

  /** Benefits that Flowform specifically provides to ecological pools */
  get benefits() {
    const l = this.lang.language();
    return [
      {
        icon: '🌀',
        title: l === 'es' ? 'Elimina el agua verde' : 'Eliminates Green Water',
        desc: l === 'es'
          ? 'La oxigenación rítmica de Flowform crea un ambiente aeróbico que inhibe el crecimiento de algas, eliminando el principal problema visual y sanitario de las piscinas ecológicas.'
          : 'Flowform\'s rhythmic oxygenation creates an aerobic environment that inhibits algae growth, eliminating the main visual and sanitary problem of ecological pools.'
      },
      {
        icon: '🫁',
        title: l === 'es' ? 'Oxigenación continua y pasiva' : 'Continuous Passive Oxygenation',
        desc: l === 'es'
          ? 'A diferencia de los sistemas mecánicos, la Flowform oxigena el agua de forma pasiva y constante con cada cascada en lemniscata. Los microorganismos aeróbicos benéficos — y no las algas — dominan el ecosistema.'
          : 'Unlike mechanical systems, Flowform oxygenates water passively and constantly with each lemniscate cascade. Beneficial aerobic microorganisms — not algae — dominate the ecosystem.'
      },
      {
        icon: '🔬',
        title: l === 'es' ? 'Potencia las plantas purificadoras' : 'Boosts Purifying Plants',
        desc: l === 'es'
          ? 'Con agua correctamente oxigenada, las plantas filtrantes (lirios, juncos, lotos) trabajan al máximo de su capacidad, absorbiendo nutrientes, nitratos y fosfatos que de otro modo alimentarían las algas.'
          : 'With properly oxygenated water, filtering plants (lilies, reeds, lotus) work at full capacity, absorbing nutrients, nitrates, and phosphates that would otherwise feed algae.'
      },
      {
        icon: '🦠',
        title: l === 'es' ? 'Control natural de patógenos' : 'Natural Pathogen Control',
        desc: l === 'es'
          ? 'El alto pH aeróbico y el oxígeno disuelto generado por Flowform crean un entorno hostil para bacterias nocivas como E. coli, sin necesidad de cloro ni productos químicos.'
          : 'The high aerobic pH and dissolved oxygen generated by Flowform create a hostile environment for harmful bacteria like E. coli, without chlorine or chemicals.'
      },
      {
        icon: '💧',
        title: l === 'es' ? 'Agua cristalina todo el año' : 'Crystal Clear Water Year-Round',
        desc: l === 'es'
          ? 'Al estabilizar el ecosistema biológico, Flowform mantiene el agua limpia, transparente y sin turbiedad durante las cuatro estaciones, incluso en verano cuando las algas son más agresivas.'
          : 'By stabilizing the biological ecosystem, Flowform keeps the water clean, transparent, and free of turbidity throughout all four seasons, even in summer when algae are most aggressive.'
      },
      {
        icon: '⚡',
        title: l === 'es' ? 'Sin mantenimiento químico' : 'No Chemical Maintenance',
        desc: l === 'es'
          ? 'Al eliminar la causa raíz del problema (falta de oxígeno), Flowform hace innecesarios los tratamientos químicos de choque que arruinan el ecosistema de la piscina ecológica.'
          : 'By eliminating the root cause of the problem (lack of oxygen), Flowform makes unnecessary the chemical shock treatments that ruin the ecological pool ecosystem.'
      }
    ];
  }

}
